In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_excel('chatgpt1.xlsx')
print(df)

                        Datetime             Tweet Id  \
0      2023-01-22 13:44:34+00:00  1617156270871689984   
1      2023-01-22 13:44:39+00:00  1617156291046129920   
2      2023-01-22 13:44:44+00:00  1617156308926340096   
3      2023-01-22 13:44:49+00:00  1617156332297250048   
4      2023-01-22 13:44:52+00:00  1617156345064570112   
...                          ...                  ...   
49996  2023-01-24 06:57:56+00:00  1617778712082089984   
49997  2023-01-24 06:57:59+00:00  1617778726393240064   
49998  2023-01-24 06:58:00+00:00  1617778728481989888   
49999  2023-01-24 06:58:01+00:00  1617778731678040064   
50000  2023-01-24 06:58:01+00:00  1617778733355790080   

                                                    Text         Username  \
0      ChatGPTで遊ぶの忘れてた！！\n書類ä...      mochico0123   
1      @AlexandrovnaIng Prohibition of ChatGPT has be...  Caput_LupinumSG   
2      Schaut Euch an, was @fobizz @DianaKnodel alles...            ciffi   
3      

In [3]:

#Creating a function that takes care of all the preprocessing stuff.
def preprocess():

  df['Text'] = df['Text'].str.lower() # Ensuring all words in the Tweet column of training data are lowercased

  # Parsing the stop_words.txt file and storing all the words in a list.
  stopwords = []
  with open('chatgpt1.xlsx','r') as file:    
      for line in file:         
          for word in line.split():            
              stopwords.append(word)

  # Removing all stopwords from all the tweets in training data.
  df["Text"] = trained["Text"].apply(lambda func: ' '.join(sw 
                                            for sw in func.split() 
                                            if sw not in stopwords))
    
  #Training Data
  df['Text'] = df['Text'].str.replace(r'http?://[^\s<>"]+|www\.[^\s<>"]+', '') # Removing hyperlinks from all the tweets
  df['Text'] = df['Text'].str.replace('@[A-Za-z0-9]+', '') # Removing usernames from all the tweets.
  df['Text'] = df['Text'].str.replace(r'\B#\w*[a-zA-Z]+\w*', '') # Removing hashtags, including the text, from all the tweets
  df['Text'] = df['Text'].str.replace('\d+', '') # Removing numbers from all the tweets


  special_chars = ["!",'"',"%","&","amp","'","(",")", "*","+",",","-",".",
                  "/",":",";","<","=",">","?","[","\\","]","^","_",
                  "`","{","|","}","~","–","@","#","$"]

  for c in special_chars:
      df['Text'] = df['Text'].str.replace(c,'') # Removing all special characters from all the tweets

In [4]:
df.head()

Datetime             Tweet Id  \
0  2023-01-22 13:44:34+00:00  1617156270871689984   
1  2023-01-22 13:44:39+00:00  1617156291046129920   
2  2023-01-22 13:44:44+00:00  1617156308926340096   
3  2023-01-22 13:44:49+00:00  1617156332297250048   
4  2023-01-22 13:44:52+00:00  1617156345064570112   

                                                Text         Username  \
0  ChatGPTで遊ぶの忘れてた！！\n書類ä...      mochico0123   
1  @AlexandrovnaIng Prohibition of ChatGPT has be...  Caput_LupinumSG   
2  Schaut Euch an, was @fobizz @DianaKnodel alles...            ciffi   
3  Bow down to chatGPT 🫡..... https://t.co/ENT...    Vishwasrisiri   
4  Profilinde vatan, Türkiye falan yazan bireyle...   0xGenetikciniz   

                                           Permalink  \
0  https://twitter.com/mochico0123/status/1617156...   
1  https://twitter.com/Caput_LupinumSG/status/161...   
2  https://twitter.com/ciffi/status/1617156308926...   
3  https://twitter.com/Vishwasrisiri/status/16171...   
4  https://twitter.com/0xGenetikciniz/status/1617...   

                                  User  \
0      https://twitter.com/mochico0123   
1  https://twitter.com/Caput_LupinumSG   
2            https://twitter.com/ciffi   
3    https://twitter.com/Vishwasrisiri   
4   https://twitter.com/0xGenetikciniz   

                                            Outlinks  \
0                                                NaN   
1                                                NaN   
2  ['https://us02web.zoom.us/webinar/register/801...   
3  ['https://twitter.com/agadmator/status/1617155...   
4                                                NaN   

                                          CountLinks  ReplyCount  \
0                                                NaN           1   
1                                                NaN           1   
2  ['https://t.co/DsoeVJrPBp', 'https://t.co/HflT...           0   
3                        ['https://t.co/ENTSzi2AQ9']           0   
4                                                NaN           0   

   RetweetCount  LikeCount  QuoteCount       ConversationId Language  \
0             0          5           0  1617156270871689984       ja   
1             0          5           0  1617148639993799936       en   
2             0          4           0  1617156308926340096       de   
3             0          2           0  1617156332297250048       en   
4             0          4           0  1617156345064570112       tr   

                                              Source  \
0  <a href="http://twitter.com/download/iphone" r...   
1  <a href="http://twitter.com/download/iphone" r...   
2  <a href="http://twitter.com/#!/download/ipad" ...   
3  <a href="http://twitter.com/download/android" ...   
4  <a href="http://twitter.com/download/iphone" r...   

                                               Media  \
0                                                NaN   
1                                                NaN   
2  [Photo(previewUrl='https://pbs.twimg.com/media...   
3                                                NaN   
4                                                NaN   

                                         QuotedTweet  \
0                                                NaN   
1                                                NaN   
2  https://twitter.com/DianaKnodel/status/1617153...   
3  https://twitter.com/agadmator/status/161715501...   
4                                                NaN   

                                      MentionedUsers       hashtag  \
0                                                NaN            []   
1  [User(username='AlexandrovnaIng', id=282705900...            []   
2  [User(username='fobizz', id=884708145792253952...  ['#ChatGPT']   
3                                                NaN            []   
4                                                NaN            []   

   hastag_counts  
0              0  
1              0  
2   

In [5]:
# shape of dataframe
df.shape

(50001, 20)

In [6]:
df.isnull().sum()

Datetime              0
Tweet Id              0
Text                  5
Username              0
Permalink             0
User                  0
Outlinks          30059
CountLinks        30059
ReplyCount            0
RetweetCount          0
LikeCount             0
QuoteCount            0
ConversationId        0
Language              0
Source                0
Media             40499
QuotedTweet       46438
MentionedUsers    32832
hashtag               0
hastag_counts         0
dtype: int64

In [7]:
y_col = 'Language'
y = df[y_col]

x_col = 'Text'
x = df [x_col]
y,x

(0        ja
 1        en
 2        de
 3        en
 4        tr
          ..
 49996    de
 49997    de
 49998    it
 49999    en
 50000    es
 Name: Language, Length: 50001, dtype: object,
 0        ChatGPTで遊ぶの忘れてた！！\n書類ä...
 1        @AlexandrovnaIng Prohibition of ChatGPT has be...
 2        Schaut Euch an, was @fobizz @DianaKnodel alles...
 3        Bow down to chatGPT 🫡..... https://t.co/ENT...
 4        Profilinde vatan, Türkiye falan yazan bireyle...
                                ...                        
 49996    #ChatGPT ist ein #Chatbot, der durch künstlic...
 49997    @r8r Ich hab mal die AI dazu befragt (ChatGPT)...
 49998    5 minuti di #chatGPT e ho capito che apprende ...
 49999    Portland Shop Uses ChatGPT To Tell Family Stor...
 50000    Ahora sueño con el día en que Amazon integre...
 Name: Text, Length: 50001, dtype: object)

In [8]:

training_data_x = x.sample(frac=0.8 , random_state=25)
training_data_x = x.drop(training_data_x.index)


testing_data_x = x.sample(frac=0.8 , random_state=25)
testing_data_x = x.drop(training_data_x.index)

print(f"No of training examples: {training_data.shape[0]}")
print(f"No of testing examples: {testing_data.shape[0]} ")

NameError: name 'training_data' is not defined

In [9]:

training_data_y = y.sample(frac=0.8 , random_state=25)
training_data_y = y.drop(training_data_x.index)


testing_data_y = y.sample(frac=0.8 , random_state=25)
testing_data_y = y.drop(training_data_x.index)

print(f"No of training examples: {training_data.shape[0]}")
print(f"No of testing examples: {testing_data.shape[0]} ")

NameError: name 'training_data' is not defined

In [10]:
def computeTF(wordDict , bagOfWords):
    tfDict ={}
    bagOfWordsCount = len(bagOfWords)
    for word , count in wordDict.items():
        tfDict[word] = count / float(bagOfWordsCount)
        return tfDict

In [11]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

# Handle missing values
training_data_x = np.where(pd.isnull(training_data_x), '', training_data_x)
testing_data_x = np.where(pd.isnull(testing_data_x), '', testing_data_x)

# create CountVectorizer object
count_vect = CountVectorizer()

# fit and transform the training data
X_train_counts = count_vect.fit_transform(training_data_x)

# transform the testing data
X_test_counts = count_vect.transform(testing_data_x)


In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

# create TfidfVectorizer object
tfidf_vect = TfidfVectorizer()

# fit and transform the training data
X_train_tfidf = tfidf_vect.fit_transform(training_data_x)

# transform the testing data
X_test_tfidf = tfidf_vect.transform(testing_data_x)


In [13]:
# Display the vectorized data for training set
print("Training set - Vectorized data:")
print(X_train_counts.toarray())

# Display the vectorized data for testing set
print("Testing set - Vectorized data:")
print(X_test_counts.toarray())


Training set - Vectorized data:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Testing set - Vectorized data:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
print("Number of samples in X_train_counts:", X_train_counts.shape[0])
print("Number of labels in training_data_y:", len(training_data_y))


Number of samples in X_train_counts: 10000
Number of labels in training_data_y: 40001


In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Initialize the Decision Tree classifier
decision_tree = DecisionTreeClassifier()

# Train the Decision Tree classifier
decision_tree.fit(X_train_counts, training_data_y[:X_train_counts.shape[0]])

# Predict on the testing set
decision_tree_preds = decision_tree.predict(X_test_counts)

# Calculate evaluation metrics
accuracy = accuracy_score(testing_data_y, decision_tree_preds)
precision = precision_score(testing_data_y, decision_tree_preds, average='macro')
recall = recall_score(testing_data_y, decision_tree_preds, average='macro')
f1 = f1_score(testing_data_y, decision_tree_preds, average='macro')

# Print the evaluation metrics
print("Decision Tree - Accuracy: {:.4f}, Precision: {:.4f}, Recall: {:.4f}, F1 Score: {:.4f}"
      .format(accuracy, precision, recall, f1))


/Users/student/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Decision Tree - Accuracy: 0.5270, Precision: 0.0163, Recall: 0.0163, F1 Score: 0.0156
